### ISSUE TITLE
mount more than one store

### ISSUE THREAD

**Issue by dkgrieshammer** [beerose/simple-zustand-devtools#7]
apparently current implementation is limited to one store right? Any chance to add more than one? Thx for your work btw 🙏

**Comment by kafinsalim** [comment]
yeah, I also searching for a way to do this. Any ideas?

**Comment by dkgrieshammer** [comment]
I made a pull request where I added documentation on how to do that but beerose hasn't merged yet; so meanwhile have a look [here](https://github.com/dkgrieshammer/simple-zustand-devtools)

**Comment by beerose** [comment]
Hey, I'm sorry for the delay. I just merged your PR @dkgrieshammer — thanks a lot!

**Comment by beerose** [comment]
However, maybe we can also modify the code so that the element id is not hardcoded to `'simple-zustand-devtools'` (https://github.com/dkgrieshammer/simple-zustand-devtools/blob/master/src/index.tsx#L40), but instead, it's dynamic based on the store name (e.g. `'simple-zustand-devtools' + storeName`). What do you think?

**Comment by beerose** [comment]
Hey, I implemented the above suggestion and published a new version (1.0.1).
